PLAYG-69-주소찾기컴포넌트
playground-PLYG/playground-nuxt pull request #10
Opened 2024-05-20 00:36 UTC by 940204yujin

우편번호 서비스 컴포넌트

2024-05-22 02:01 UTC, 940204yujin commented
리뷰 작성 요청 드립니다.

2024-05-22 02:15 UTC, hsm0711 requested changes
1. PostCode컴포넌트에 도로명 주소 여부 받아서 도로명 주소일 때만 지번 선택 시 도로명 주소 alert
2. PostCode컴포넌트 결과데이터를 postCode-test에서 받을 수 있도록 추가
3. 2번의 결과는 아래 JSON 형식으로 구성
`
 {
  zonecode: 우편번호\n
  address: 선택한 주소\n
  detailAddress: 입력한 상세 주소
  userSelectedType: 선택한 주소 타입 (지번:J, 도로명:R)
  roadAddress: 검색된 도로명 주소, 없는 경우 empty string('')
  jibunAddress: 검색된 지번 주소, 없는 경우 empty string('')
 }
`

2024-05-24 02:06 UTC, 940204yujin commented
피드백 사항 반영하여 수정했습니다! 리뷰 요청합니다.

2024-05-24 02:44 UTC, hsm0711 requested changes
주소찾기 팝업 layer팝업으로 구성

2024-05-24 03:20 UTC, hsm0711 requested changes
주소찾기 팝업 layer팝업으로 구성

2024-05-28 01:07 UTC, 940204yujin commented
리뷰 요청 드립니다 !

2024-05-28 05:59 UTC, hsm0711 requested changes
도로명주소로만 옵션 설정 후 지번 선택하면 도러명 주소 선택하라는 alert뜬 후 alert의 확인 선택하면 도로명주소 팝업이 닫힘. 안닫히도록 수정.

2024-05-28 08:07 UTC, 940204yujin commented
지번 선택 시 주소팝업 닫힘 수정하였습니다 리뷰 요청합니다 !

2024-05-28 08:13 UTC, hsm0711 approved these changes

2024-05-28 08:14 UTC, merged