PLAYG-75-notice-board
playground-PLYG/playground-nuxt pull request #40
Opened 2024-06-12 08:28 UTC by kimsoohwan6198

2024-06-12 23:41 UTC, hsm0711 requested changes
layouts/default.vue rollback

2024-06-13 01:07 UTC, hsm0711 requested changes
style scss구조로 변경 및 scoped 지정

2024-06-13 06:51 UTC, hsm0711 requested changes
- <template> 하위 첫 레벨은 하나의 태그만 생성
```html
 // bad
 <template>
	<div>
		<span></span>
	<div/>
	<div>
		<span></span>
		<span></span>
	<div/>
 <template>
 
 // good
 <template>
	<div>
		<div>
			<span></span>
		<div/>
		<div>
			<span></span>
			<span></span>
		<div/>
	<div/>
 <template>
```
- 불필요한 <template>제거
- <template> 안쪽에 component선언 시 kebab case로 선언
```html
<CommentItem /> => <coment-item />
```    
- notice/index.vue style도 scss로 수정, scoped추가
- quasar에서 정의된 class style 조작 금지 - https://quasar.dev/style/spacing
style변경이 필요한 경우 새로운 class할당해서 적용
ex) q-~~
- lint, prettier 적용 - https://discord.com/channels/1134021025810620417/1232618541211979797/1244919857015820371
    - ref로 할당한 변수는 const로 선언
    - onMounted에 불필요한 async제거 -> async는 await이 있을때 사용
    - console.log 제거
    - 그외...

2024-06-14 05:29 UTC, park-junwon approved these changes

2024-06-17 00:00 UTC, hsm0711 approved these changes

2024-06-18 01:16 UTC, merged